export const uiCopy = {
  es: {
    appTitle: "Menú Interactivo",
    studioTitle: "Menú Interactivo",
    studioSubtitle: "Centro de control del proyecto.",
    landingTitle: "Menu Maker",
    landingBy: "By keneth4",
    landingCreate: "Crear proyecto",
    landingOpen: "Abrir proyecto",
    landingWizard: "Iniciar wizard",
    tabProject: "Proyecto",
    tabAssets: "Assets",
    tabEdit: "Edición",
    tabWizard: "Wizard",
    newProject: "Nuevo",
    open: "Abrir",
    save: "Guardar",
    export: "Exportar sitio",
    toggleView: "Cambiar vista",
    toggleLang: "Cambiar idioma UI",
    openEditor: "Abrir editor",
    closeEditor: "Cerrar editor",
    loadingProject: "Cargando proyecto...",
    uploadAssets: "Subir assets",
    uploadHint: "Arrastra archivos o usa el botón para subir.",
    uploadTo: "Subir a",
    promptMoveTo: "Mover a (ruta dentro de la carpeta raíz)",
    step: "Paso",
    wizardProgress: "Progreso",
    wizardNext: "Siguiente",
    wizardBack: "Anterior",
    wizardComplete: "Completo",
    wizardMissingBackground: "Agrega al menos un fondo con src.",
    wizardRequireRootBackground:
      "Sube y selecciona al menos un fondo propio para dejar de usar el demo.",
    wizardDemoPreviewHint:
      "Vista demo activa: sube tus assets y selecciona al menos un fondo para usar tu carpeta raíz.",
    wizardMissingCategories: "Crea al menos una sección con nombre.",
    wizardMissingDishes: "Agrega al menos un item con nombre y precio visible.",
    exporting: "Exportando...",
    exportReady: "Exportación lista.",
    exportFailed: "No se pudo exportar.",
    progressSaveLabel: "Guardando proyecto",
    progressExportLabel: "Exportando sitio",
    progressUploadLabel: "Abriendo proyecto",
    progressSaveStart: "Preparando guardado...",
    progressSaveDerive: "Procesando assets derivados...",
    progressSaveSync: "Actualizando datos del proyecto...",
    progressSaveZip: "Empaquetando archivos...",
    progressSaveDownload: "Iniciando descarga...",
    progressSaveDone: "Guardado listo.",
    progressUploadStart: "Leyendo zip del proyecto...",
    progressUploadAssets: "Subiendo assets...",
    progressUploadDerive: "Generando assets derivados...",
    progressUploadApply: "Aplicando proyecto...",
    progressUploadDone: "Proyecto cargado.",
    progressExportStart: "Preparando exportación...",
    progressExportDerive: "Procesando assets derivados...",
    progressExportCollect: "Recolectando assets...",
    progressExportBundle: "Generando sitio estático...",
    progressExportReport: "Validando rendimiento...",
    progressExportDownload: "Preparando descarga...",
    progressExportDone: "Exportación lista.",
    tipRotate: "Consejo: gira el dispositivo a horizontal para ver el layout completo.",
    selectFolder: "Seleccionar carpeta",
    newFolder: "Nueva carpeta",
    rootTitle: "Assets del proyecto",
    rootNone: "Sin ubicación",
    dragDrop: "Arrastra archivos aquí o usa el botón de subir.",
    selectAll: "Seleccionar todo",
    clear: "Limpiar",
    move: "Mover",
    delete: "Eliminar",
    rename: "Renombrar",
    pickRootHint: "Sube assets para verlos aquí.",
    rootEmpty: "Sin archivos en este proyecto.",
    filesCount: "archivos",
    projectName: "Nombre del proyecto",
    template: "Template",
    languages: "Idiomas disponibles",
    languagesNoneSelected: "Ningún idioma seleccionado",
    defaultLang: "Idioma default",
    defaultLangFallback: "Idioma de interfaz (fallback)",
    languageRequiredHint: "Selecciona al menos un idioma para habilitar Guardar y Exportar.",
    selectImagePlaceholder: "Selecciona una imagen",
    font: "Tipografía",
    textStyle: "Estilo de texto",
    textStyleDefault: "Default (heredado del proyecto/rol)",
    fontPreviewSample: "Lorem ipsum dolor sit.",
    scrollSensitivityItem: "Sensibilidad scroll/drag de items",
    scrollSensitivitySection: "Sensibilidad scroll/drag de secciones",
    scrollSensitivityHint: "1 = menos sensible, 10 = más sensible",
    fontCustom: "Fuente personalizada",
    fontCustomName: "Nombre de fuente",
    fontCustomSrc: "Archivo de fuente",
    fontRoleIdentity: "Fuente de identidad",
    fontRoleIdentityHint:
      "Aplica al bloque de identidad y sirve como fallback para nombre de restaurante y título.",
    fontRoleIdentitySrc: "Archivo de fuente de identidad",
    fontRoleRestaurant: "Fuente del título",
    fontRoleTitle: "Fuente del subtítulo",
    fontRoleSection: "Fuente de secciones",
    fontRoleItem: "Fuente de items",
    fontRoleItemSrc: "Archivo de fuente de items",
    restaurantName: "Título",
    menuTitle: "Subtítulo",
    identityMode: "Modo de identidad",
    identityModeText: "Texto",
    identityModeLogo: "Logo",
    logoAsset: "Asset del logo",
    menuTitleFallback: "Menú",
    restaurantFallback: "Restaurante",
    blankMenu: "Selecciona una plantilla para comenzar.",
    currency: "Moneda",
    currencyPos: "Posición del símbolo",
    currencyLeft: "Izquierda (€150)",
    currencyRight: "Derecha (150€)",
    editLang: "Idioma de edición",
    editIdentity: "Identidad",
    editBackgrounds: "Fondos",
    backgroundDisplayMode: "Modo de fondos",
    backgroundDisplayCarousel: "Carrusel",
    backgroundDisplaySection: "Por sección",
    backgroundCarouselDuration: "Duración del carrusel (segundos)",
    backgroundCarouselDurationHint: "Tiempo que permanece visible cada fondo antes del siguiente.",
    backgroundOrder: "Orden del carrusel",
    moveBackgroundUp: "Mover fondo arriba",
    moveBackgroundDown: "Mover fondo abajo",
    secondsShort: "s",
    editSections: "Secciones",
    editDishes: "Items",
    editHierarchyHint: "Jerarquía: Sección > Item",
    backgroundHint: "Gestiona el carrusel de fondos del preview.",
    sectionHint: "Renombra y organiza las secciones del menú.",
    dishHint: "Edita items dentro de la sección seleccionada.",
    editItemsNeedsSections: "Crea al menos una sección para habilitar Items.",
    section: "Sección",
    sectionBackground: "Fondo de sección",
    sectionBackgroundNeedsCoverage: "El modo por sección requiere un fondo válido por sección.",
    sectionBackgroundNeedsUnique: "Cada sección debe usar un fondo diferente.",
    sectionName: "Nombre de sección",
    deleteSection: "Eliminar sección",
    editSection: "Editar sección",
    dish: "Item",
    dishData: "Datos del item",
    name: "Nombre",
    description: "Descripción",
    longDescription: "Historia / descripción larga",
    allergensLabel: "Alérgenos",
    commonAllergens: "Alérgenos comunes",
    customAllergens: "Alérgenos personalizados",
    customAllergensHint: "Escribe separados por coma y tradúcelos en cada idioma.",
    veganLabel: "Vegano",
    showPrice: "Mostrar precio",
    price: "Precio",
    asset360: "Asset 360",
    itemScrollAnimationMode: "Animación de scroll",
    itemScrollAnimationModeHero: "Usar 360",
    itemScrollAnimationModeAlternate: "Usar alternativo",
    itemScrollAnimationSrc: "Asset alternativo",
    itemFontOverrideName: "Fuente del item",
    itemFontOverrideSrc: "Archivo de fuente del item",
    rotationDirection: "Dirección de giro",
    rotationCounterclockwise: "Antihorario",
    rotationClockwise: "Horario",
    rotationChooseHint: "Elige el giro que coincide con este asset 360.",
    addSection: "Agregar sección",
    addDish: "Agregar item",
    prevDish: "Item anterior",
    nextDish: "Item siguiente",
    wizardPick: "Elige una estructura base para comenzar.",
    wizardTip: "Tip: si ya tienes categorías, el template solo cambia el estilo.",
    wizardIdentity: "Define identidad y fondos.",
    wizardCategories: "Crea categorías principales.",
    wizardDishes: "Agrega items y sus GIFs 360.",
    wizardPreview: "Revisa el preview final.",
    wizardAssetsHint: "Sube assets en la pestaña Assets para seleccionarlos aquí.",
    wizardStepStructure: "Estructura",
    wizardStepIdentity: "Identidad",
    wizardStepCategories: "Categorías",
    wizardStepDishes: "Items",
    wizardStepPreview: "Preview",
    wizardAddBg: "Agregar fondo",
    wizardLabel: "Label",
    wizardSrc: "Src",
    wizardLanguage: "Idioma",
    wizardCategory: "Categoría",
    wizardAddCategory: "Agregar categoría",
    wizardAddDish: "Agregar item",
    wizardExportNote: "El exportador del sitio estático se agregará en este paso.",
    backgroundLabel: "Fondo",
    errOpenProject: "No se pudo abrir el archivo",
    errNoFolder: "Tu navegador no soporta acceso a carpetas locales.",
    errOpenFolder: "No se pudo abrir la carpeta.",
    errAssetScope:
      "Solo puedes gestionar archivos dentro de originals/backgrounds, originals/items, originals/fonts y originals/logos.",
    errAssetRootProtected:
      "Las carpetas base originals, originals/backgrounds, originals/items, originals/fonts y originals/logos no se pueden mover, renombrar ni borrar.",
    errMoveFolder: "Tu navegador no soporta mover archivos por carpeta.",
    errZipMissing: "El zip no contiene menu.json.",
    errZipCompression: "El zip usa compresión no soportada. Usa un zip sin compresión.",
    errZipNoBridge: "Para abrir zips necesitas el almacenamiento local activo.",
    errSelectLanguage: "Selecciona al menos un idioma antes de guardar o exportar.",
    assetsRequired: "Carga los assets del proyecto para completar el preview.",
    assetsReadOnly:
      "Este proyecto demo es de solo lectura. No puedes modificar ni borrar sus assets.",
    assetsOwnershipNotice:
      "Los assets pertenecen a sus propietarios. No copies ni reutilices este contenido sin autorización.",
    promptNewFolder: "Nombre de la nueva carpeta",
    promptRename: "Nuevo nombre",
    promptSaveName: "Nombre del archivo del proyecto (zip)",
    close: "Cerrar"
  },
  en: {
    appTitle: "Interactive Menu",
    studioTitle: "Interactive Menu",
    studioSubtitle: "Project control center.",
    landingTitle: "Menu Maker",
    landingBy: "By keneth4",
    landingCreate: "Create project",
    landingOpen: "Open project",
    landingWizard: "Run wizard",
    tabProject: "Project",
    tabAssets: "Assets",
    tabEdit: "Edit",
    tabWizard: "Wizard",
    newProject: "New",
    open: "Open",
    save: "Save",
    export: "Export site",
    toggleView: "Toggle view",
    toggleLang: "Toggle UI language",
    openEditor: "Open editor",
    closeEditor: "Close editor",
    loadingProject: "Loading project...",
    uploadAssets: "Upload assets",
    uploadHint: "Drag files here or use the upload button.",
    uploadTo: "Upload to",
    promptMoveTo: "Move to (path inside root folder)",
    step: "Step",
    wizardProgress: "Progress",
    wizardNext: "Next",
    wizardBack: "Back",
    wizardComplete: "Complete",
    wizardMissingBackground: "Add at least one background with src.",
    wizardRequireRootBackground:
      "Upload and select at least one of your own backgrounds to stop using demo assets.",
    wizardDemoPreviewHint:
      "Demo preview is active: upload your assets and pick at least one background from your root folder.",
    wizardMissingCategories: "Create at least one section with a name.",
    wizardMissingDishes: "Add at least one item with name and visible price.",
    exporting: "Exporting...",
    exportReady: "Export ready.",
    exportFailed: "Export failed.",
    progressSaveLabel: "Saving project",
    progressExportLabel: "Exporting site",
    progressUploadLabel: "Opening project",
    progressSaveStart: "Preparing save...",
    progressSaveDerive: "Processing derived assets...",
    progressSaveSync: "Updating project data...",
    progressSaveZip: "Packaging files...",
    progressSaveDownload: "Starting download...",
    progressSaveDone: "Save ready.",
    progressUploadStart: "Reading project zip...",
    progressUploadAssets: "Uploading assets...",
    progressUploadDerive: "Generating derived assets...",
    progressUploadApply: "Applying project...",
    progressUploadDone: "Project loaded.",
    progressExportStart: "Preparing export...",
    progressExportDerive: "Processing derived assets...",
    progressExportCollect: "Collecting assets...",
    progressExportBundle: "Building static site...",
    progressExportReport: "Validating performance...",
    progressExportDownload: "Preparing download...",
    progressExportDone: "Export ready.",
    tipRotate: "Tip: rotate the device to landscape to see the full layout.",
    selectFolder: "Select folder",
    newFolder: "New folder",
    rootTitle: "Project assets",
    rootNone: "No location",
    dragDrop: "Drag files here or use the upload button.",
    selectAll: "Select all",
    clear: "Clear",
    move: "Move",
    delete: "Delete",
    rename: "Rename",
    pickRootHint: "Upload assets to see them here.",
    rootEmpty: "No files in this project yet.",
    filesCount: "files",
    projectName: "Project name",
    template: "Template",
    languages: "Available languages",
    languagesNoneSelected: "No languages selected",
    defaultLang: "Default language",
    defaultLangFallback: "Interface language (fallback)",
    languageRequiredHint: "Select at least one language to enable Save and Export.",
    selectImagePlaceholder: "Select an image",
    font: "Typography",
    textStyle: "Text style",
    textStyleDefault: "Default (project/role fallback)",
    fontPreviewSample: "Lorem ipsum dolor sit.",
    scrollSensitivityItem: "Item scroll/drag sensitivity",
    scrollSensitivitySection: "Section scroll/drag sensitivity",
    scrollSensitivityHint: "1 = less sensitive, 10 = more sensitive",
    fontCustom: "Custom font",
    fontCustomName: "Font name",
    fontCustomSrc: "Font file",
    fontRoleIdentity: "Identity font",
    fontRoleIdentityHint:
      "Applies to the identity block and acts as fallback for restaurant name and menu title.",
    fontRoleIdentitySrc: "Identity font file",
    fontRoleRestaurant: "Title font",
    fontRoleTitle: "Subtitle font",
    fontRoleSection: "Sections font",
    fontRoleItem: "Items font",
    fontRoleItemSrc: "Items font file",
    restaurantName: "Title",
    menuTitle: "Subtitle",
    identityMode: "Identity mode",
    identityModeText: "Text",
    identityModeLogo: "Logo",
    logoAsset: "Logo asset",
    menuTitleFallback: "Menu",
    restaurantFallback: "Restaurant",
    blankMenu: "Select a template to begin.",
    currency: "Currency",
    currencyPos: "Symbol position",
    currencyLeft: "Left (€150)",
    currencyRight: "Right (150€)",
    editLang: "Editing language",
    editIdentity: "Identity",
    editBackgrounds: "Backgrounds",
    backgroundDisplayMode: "Background mode",
    backgroundDisplayCarousel: "Carousel",
    backgroundDisplaySection: "Per section",
    backgroundCarouselDuration: "Carousel duration (seconds)",
    backgroundCarouselDurationHint: "How long each background stays visible before switching.",
    backgroundOrder: "Carousel order",
    moveBackgroundUp: "Move background up",
    moveBackgroundDown: "Move background down",
    secondsShort: "s",
    editSections: "Sections",
    editDishes: "Items",
    editHierarchyHint: "Hierarchy: Section > Item",
    backgroundHint: "Manage the preview background carousel.",
    sectionHint: "Rename and organize menu sections.",
    dishHint: "Edit items inside the selected section.",
    editItemsNeedsSections: "Create at least one section to enable Items.",
    section: "Section",
    sectionBackground: "Section background",
    sectionBackgroundNeedsCoverage: "Section mode requires one valid background per section.",
    sectionBackgroundNeedsUnique: "Each section must use a different background.",
    sectionName: "Section name",
    deleteSection: "Delete section",
    editSection: "Edit section",
    dish: "Item",
    dishData: "Item details",
    name: "Name",
    description: "Description",
    longDescription: "History / long description",
    allergensLabel: "Allergens",
    commonAllergens: "Common Allergens",
    customAllergens: "Custom Allergens",
    customAllergensHint: "Use comma-separated names and translate them for each language.",
    veganLabel: "Vegan",
    showPrice: "Show price",
    price: "Price",
    asset360: "360 asset",
    itemScrollAnimationMode: "Scroll animation",
    itemScrollAnimationModeHero: "Use 360",
    itemScrollAnimationModeAlternate: "Use alternate",
    itemScrollAnimationSrc: "Alternate asset",
    itemFontOverrideName: "Item font",
    itemFontOverrideSrc: "Item font file",
    rotationDirection: "Rotation direction",
    rotationCounterclockwise: "Counterclockwise",
    rotationClockwise: "Clockwise",
    rotationChooseHint: "Choose the direction that matches this 360 asset.",
    addSection: "Add section",
    addDish: "Add item",
    prevDish: "Previous item",
    nextDish: "Next item",
    wizardPick: "Choose a base structure to start.",
    wizardTip: "Tip: if you already have categories, the template only changes layout.",
    wizardIdentity: "Define identity and backgrounds.",
    wizardCategories: "Create main categories.",
    wizardDishes: "Add items and their 360 GIFs.",
    wizardPreview: "Review the final preview.",
    wizardAssetsHint: "Upload assets in the Assets tab to select them here.",
    wizardStepStructure: "Structure",
    wizardStepIdentity: "Identity",
    wizardStepCategories: "Categories",
    wizardStepDishes: "Items",
    wizardStepPreview: "Preview",
    wizardAddBg: "Add background",
    wizardLabel: "Label",
    wizardSrc: "Src",
    wizardLanguage: "Language",
    wizardCategory: "Category",
    wizardAddCategory: "Add category",
    wizardAddDish: "Add item",
    wizardExportNote: "The static site exporter will be added in this step.",
    backgroundLabel: "Background",
    errOpenProject: "Unable to open the file",
    errNoFolder: "Your browser doesn't support local folder access.",
    errOpenFolder: "Unable to open the folder.",
    errAssetScope:
      "You can only manage files inside originals/backgrounds, originals/items, originals/fonts, and originals/logos.",
    errAssetRootProtected:
      "Base folders originals, originals/backgrounds, originals/items, originals/fonts, and originals/logos cannot be moved, renamed, or deleted.",
    errMoveFolder: "Your browser doesn't support moving files by folder.",
    errZipMissing: "The zip file doesn't contain menu.json.",
    errZipCompression: "The zip uses unsupported compression. Use a stored zip.",
    errZipNoBridge: "Zip import requires local bridge storage.",
    errSelectLanguage: "Select at least one language before saving or exporting.",
    assetsRequired: "Upload the project assets to complete the preview.",
    assetsReadOnly:
      "This demo project is read-only. You cannot modify or delete its assets.",
    assetsOwnershipNotice:
      "Assets belong to their owners. Do not copy or reuse this content without permission.",
    promptNewFolder: "New folder name",
    promptRename: "New name",
    promptSaveName: "Project file name (zip)",
    close: "Close"
  }
};

export type UiKey = keyof (typeof uiCopy)["es"];
