export const uiCopy = {
  es: {
    appTitle: "Menú Interactivo",
    studioTitle: "Menú Interactivo",
    studioSubtitle: "Centro de control del proyecto.",
    landingTitle: "Menu Maker",
    landingBy: "By keneth4",
    landingCreate: "Crear proyecto",
    landingOpen: "Abrir proyecto",
    landingWizard: "Iniciar wizard",
    tabProject: "Proyecto",
    tabAssets: "Assets",
    tabEdit: "Edición",
    tabWizard: "Wizard",
    newProject: "Nuevo proyecto",
    open: "Abrir proyecto",
    save: "Guardar proyecto",
    export: "Exportar sitio",
    toggleView: "Cambiar vista",
    toggleLang: "Cambiar idioma UI",
    openEditor: "Abrir editor",
    closeEditor: "Cerrar editor",
    loadingProject: "Cargando proyecto...",
    uploadAssets: "Subir assets",
    uploadHint: "Arrastra archivos o usa el botón para subir.",
    uploadTo: "Subir a",
    promptMoveTo: "Mover a (ruta dentro de la carpeta raíz)",
    step: "Paso",
    wizardProgress: "Progreso",
    wizardNext: "Siguiente",
    wizardBack: "Anterior",
    wizardComplete: "Completo",
    wizardMissingBackground: "Agrega al menos un fondo con src.",
    wizardRequireRootBackground:
      "Sube y selecciona al menos un fondo propio para dejar de usar el demo.",
    wizardDemoPreviewHint:
      "Vista demo activa: sube tus assets y selecciona al menos un fondo para usar tu carpeta raíz.",
    wizardMissingCategories: "Crea al menos una sección con nombre.",
    wizardMissingDishes: "Agrega al menos un platillo con nombre y precio.",
    exporting: "Exportando...",
    exportReady: "Exportación lista.",
    exportFailed: "No se pudo exportar.",
    progressSaveLabel: "Guardando proyecto",
    progressExportLabel: "Exportando sitio",
    progressUploadLabel: "Abriendo proyecto",
    progressSaveStart: "Preparando guardado...",
    progressSaveDerive: "Procesando assets derivados...",
    progressSaveSync: "Actualizando datos del proyecto...",
    progressSaveZip: "Empaquetando archivos...",
    progressSaveDownload: "Iniciando descarga...",
    progressSaveDone: "Guardado listo.",
    progressUploadStart: "Leyendo zip del proyecto...",
    progressUploadAssets: "Subiendo assets...",
    progressUploadDerive: "Generando assets derivados...",
    progressUploadApply: "Aplicando proyecto...",
    progressUploadDone: "Proyecto cargado.",
    progressExportStart: "Preparando exportación...",
    progressExportDerive: "Procesando assets derivados...",
    progressExportCollect: "Recolectando assets...",
    progressExportBundle: "Generando sitio estático...",
    progressExportReport: "Validando rendimiento...",
    progressExportDownload: "Preparando descarga...",
    progressExportDone: "Exportación lista.",
    tipRotate: "Consejo: gira el dispositivo a horizontal para ver el layout completo.",
    selectFolder: "Seleccionar carpeta",
    newFolder: "Nueva carpeta",
    rootTitle: "Assets del proyecto",
    rootNone: "Sin ubicación",
    dragDrop: "Arrastra archivos aquí o usa el botón de subir.",
    selectAll: "Seleccionar todo",
    clear: "Limpiar",
    move: "Mover",
    delete: "Eliminar",
    rename: "Renombrar",
    pickRootHint: "Sube assets para verlos aquí.",
    rootEmpty: "Sin archivos en este proyecto.",
    filesCount: "archivos",
    projectName: "Nombre del proyecto",
    template: "Template",
    languages: "Idiomas disponibles",
    defaultLang: "Idioma default",
    font: "Tipografía",
    fontCustom: "Fuente personalizada",
    fontCustomName: "Nombre de fuente",
    fontCustomSrc: "Archivo de fuente",
    restaurantName: "Nombre del restaurante",
    menuTitle: "Título del menú",
    identityMode: "Modo de identidad",
    identityModeText: "Texto",
    identityModeLogo: "Logo",
    logoAsset: "Asset del logo",
    menuTitleFallback: "Menú",
    restaurantFallback: "Restaurante",
    blankMenu: "Selecciona una plantilla para comenzar.",
    currency: "Moneda",
    currencyPos: "Posición del símbolo",
    currencyLeft: "Izquierda (€150)",
    currencyRight: "Derecha (150€)",
    editLang: "Idioma de edición",
    editIdentity: "Identidad",
    editSections: "Secciones",
    editDishes: "Platillos",
    editHierarchyHint: "Jerarquía: Sección > Platillo",
    sectionHint: "Renombra y organiza las secciones del menú.",
    dishHint: "Edita platillos dentro de la sección seleccionada.",
    section: "Sección",
    sectionName: "Nombre de sección",
    deleteSection: "Eliminar sección",
    dish: "Platillo",
    dishData: "Datos del platillo",
    name: "Nombre",
    description: "Descripción",
    longDescription: "Historia / descripción larga",
    allergensLabel: "Alérgenos",
    commonAllergens: "Alérgenos comunes",
    customAllergens: "Alérgenos personalizados",
    customAllergensHint: "Escribe separados por coma y tradúcelos en cada idioma.",
    veganLabel: "Vegano",
    price: "Precio",
    asset360: "Asset 360",
    rotationDirection: "Dirección de giro",
    rotationCounterclockwise: "Antihorario",
    rotationClockwise: "Horario",
    rotationChooseHint: "Elige el giro que coincide con este asset 360.",
    addSection: "Agregar sección",
    addDish: "Agregar platillo",
    prevDish: "Platillo anterior",
    nextDish: "Platillo siguiente",
    wizardPick: "Elige una estructura base para comenzar.",
    wizardTip: "Tip: si ya tienes categorías, el template solo cambia el estilo.",
    wizardIdentity: "Define identidad y fondos.",
    wizardCategories: "Crea categorías principales.",
    wizardDishes: "Agrega platillos y sus GIFs 360.",
    wizardPreview: "Revisa el preview final.",
    wizardAssetsHint: "Sube assets en la pestaña Assets para seleccionarlos aquí.",
    wizardStepStructure: "Estructura",
    wizardStepIdentity: "Identidad",
    wizardStepCategories: "Categorías",
    wizardStepDishes: "Platillos",
    wizardStepPreview: "Preview",
    wizardAddBg: "+ Fondo",
    wizardLabel: "Label",
    wizardSrc: "Src",
    wizardLanguage: "Idioma",
    wizardCategory: "Categoría",
    wizardAddCategory: "+ Categoría",
    wizardAddDish: "+ Platillo",
    wizardExportNote: "El exportador del sitio estático se agregará en este paso.",
    backgroundLabel: "Fondo",
    errOpenProject: "No se pudo abrir el archivo",
    errNoFolder: "Tu navegador no soporta acceso a carpetas locales.",
    errOpenFolder: "No se pudo abrir la carpeta.",
    errAssetScope: "Solo puedes gestionar archivos dentro de originals/backgrounds y originals/items.",
    errAssetRootProtected:
      "Las carpetas base originals/backgrounds y originals/items no se pueden mover, renombrar ni borrar.",
    errMoveFolder: "Tu navegador no soporta mover archivos por carpeta.",
    errZipMissing: "El zip no contiene menu.json.",
    errZipCompression: "El zip usa compresión no soportada. Usa un zip sin compresión.",
    errZipNoBridge: "Para abrir zips necesitas el almacenamiento local activo.",
    assetsRequired: "Carga los assets del proyecto para completar el preview.",
    assetsReadOnly:
      "Este proyecto demo es de solo lectura. No puedes modificar ni borrar sus assets.",
    assetsOwnershipNotice:
      "Los assets pertenecen a sus propietarios. No copies ni reutilices este contenido sin autorización.",
    promptNewFolder: "Nombre de la nueva carpeta",
    promptRename: "Nuevo nombre",
    promptSaveName: "Nombre del archivo del proyecto (zip)"
  },
  en: {
    appTitle: "Interactive Menu",
    studioTitle: "Interactive Menu",
    studioSubtitle: "Project control center.",
    landingTitle: "Menu Maker",
    landingBy: "By keneth4",
    landingCreate: "Create project",
    landingOpen: "Open project",
    landingWizard: "Run wizard",
    tabProject: "Project",
    tabAssets: "Assets",
    tabEdit: "Edit",
    tabWizard: "Wizard",
    newProject: "New project",
    open: "Open project",
    save: "Save project",
    export: "Export site",
    toggleView: "Toggle view",
    toggleLang: "Toggle UI language",
    openEditor: "Open editor",
    closeEditor: "Close editor",
    loadingProject: "Loading project...",
    uploadAssets: "Upload assets",
    uploadHint: "Drag files here or use the upload button.",
    uploadTo: "Upload to",
    promptMoveTo: "Move to (path inside root folder)",
    step: "Step",
    wizardProgress: "Progress",
    wizardNext: "Next",
    wizardBack: "Back",
    wizardComplete: "Complete",
    wizardMissingBackground: "Add at least one background with src.",
    wizardRequireRootBackground:
      "Upload and select at least one of your own backgrounds to stop using demo assets.",
    wizardDemoPreviewHint:
      "Demo preview is active: upload your assets and pick at least one background from your root folder.",
    wizardMissingCategories: "Create at least one section with a name.",
    wizardMissingDishes: "Add at least one dish with name and price.",
    exporting: "Exporting...",
    exportReady: "Export ready.",
    exportFailed: "Export failed.",
    progressSaveLabel: "Saving project",
    progressExportLabel: "Exporting site",
    progressUploadLabel: "Opening project",
    progressSaveStart: "Preparing save...",
    progressSaveDerive: "Processing derived assets...",
    progressSaveSync: "Updating project data...",
    progressSaveZip: "Packaging files...",
    progressSaveDownload: "Starting download...",
    progressSaveDone: "Save ready.",
    progressUploadStart: "Reading project zip...",
    progressUploadAssets: "Uploading assets...",
    progressUploadDerive: "Generating derived assets...",
    progressUploadApply: "Applying project...",
    progressUploadDone: "Project loaded.",
    progressExportStart: "Preparing export...",
    progressExportDerive: "Processing derived assets...",
    progressExportCollect: "Collecting assets...",
    progressExportBundle: "Building static site...",
    progressExportReport: "Validating performance...",
    progressExportDownload: "Preparing download...",
    progressExportDone: "Export ready.",
    tipRotate: "Tip: rotate the device to landscape to see the full layout.",
    selectFolder: "Select folder",
    newFolder: "New folder",
    rootTitle: "Project assets",
    rootNone: "No location",
    dragDrop: "Drag files here or use the upload button.",
    selectAll: "Select all",
    clear: "Clear",
    move: "Move",
    delete: "Delete",
    rename: "Rename",
    pickRootHint: "Upload assets to see them here.",
    rootEmpty: "No files in this project yet.",
    filesCount: "files",
    projectName: "Project name",
    template: "Template",
    languages: "Available languages",
    defaultLang: "Default language",
    font: "Typography",
    fontCustom: "Custom font",
    fontCustomName: "Font name",
    fontCustomSrc: "Font file",
    restaurantName: "Restaurant name",
    menuTitle: "Menu title",
    identityMode: "Identity mode",
    identityModeText: "Text",
    identityModeLogo: "Logo",
    logoAsset: "Logo asset",
    menuTitleFallback: "Menu",
    restaurantFallback: "Restaurant",
    blankMenu: "Select a template to begin.",
    currency: "Currency",
    currencyPos: "Symbol position",
    currencyLeft: "Left (€150)",
    currencyRight: "Right (150€)",
    editLang: "Editing language",
    editIdentity: "Identity",
    editSections: "Sections",
    editDishes: "Dishes",
    editHierarchyHint: "Hierarchy: Section > Dish",
    sectionHint: "Rename and organize menu sections.",
    dishHint: "Edit dishes inside the selected section.",
    section: "Section",
    sectionName: "Section name",
    deleteSection: "Delete section",
    dish: "Dish",
    dishData: "Dish details",
    name: "Name",
    description: "Description",
    longDescription: "History / long description",
    allergensLabel: "Allergens",
    commonAllergens: "Common Allergens",
    customAllergens: "Custom Allergens",
    customAllergensHint: "Use comma-separated names and translate them for each language.",
    veganLabel: "Vegan",
    price: "Price",
    asset360: "360 asset",
    rotationDirection: "Rotation direction",
    rotationCounterclockwise: "Counterclockwise",
    rotationClockwise: "Clockwise",
    rotationChooseHint: "Choose the direction that matches this 360 asset.",
    addSection: "Add section",
    addDish: "Add dish",
    prevDish: "Previous dish",
    nextDish: "Next dish",
    wizardPick: "Choose a base structure to start.",
    wizardTip: "Tip: if you already have categories, the template only changes layout.",
    wizardIdentity: "Define identity and backgrounds.",
    wizardCategories: "Create main categories.",
    wizardDishes: "Add dishes and their 360 GIFs.",
    wizardPreview: "Review the final preview.",
    wizardAssetsHint: "Upload assets in the Assets tab to select them here.",
    wizardStepStructure: "Structure",
    wizardStepIdentity: "Identity",
    wizardStepCategories: "Categories",
    wizardStepDishes: "Dishes",
    wizardStepPreview: "Preview",
    wizardAddBg: "+ Background",
    wizardLabel: "Label",
    wizardSrc: "Src",
    wizardLanguage: "Language",
    wizardCategory: "Category",
    wizardAddCategory: "+ Category",
    wizardAddDish: "+ Dish",
    wizardExportNote: "The static site exporter will be added in this step.",
    backgroundLabel: "Background",
    errOpenProject: "Unable to open the file",
    errNoFolder: "Your browser doesn't support local folder access.",
    errOpenFolder: "Unable to open the folder.",
    errAssetScope: "You can only manage files inside originals/backgrounds and originals/items.",
    errAssetRootProtected:
      "Base folders originals/backgrounds and originals/items cannot be moved, renamed, or deleted.",
    errMoveFolder: "Your browser doesn't support moving files by folder.",
    errZipMissing: "The zip file doesn't contain menu.json.",
    errZipCompression: "The zip uses unsupported compression. Use a stored zip.",
    errZipNoBridge: "Zip import requires local bridge storage.",
    assetsRequired: "Upload the project assets to complete the preview.",
    assetsReadOnly:
      "This demo project is read-only. You cannot modify or delete its assets.",
    assetsOwnershipNotice:
      "Assets belong to their owners. Do not copy or reuse this content without permission.",
    promptNewFolder: "New folder name",
    promptRename: "New name",
    promptSaveName: "Project file name (zip)"
  }
};

export type UiKey = keyof (typeof uiCopy)["es"];
